### ISSUE TITLE
Not sure if working anymore

### ISSUE THREAD

**Issue by collinrijock** [Djaenk/zyBooks-Activity-Completer#9]
Hey dude thanks for this project my friend recommended it after he used it a year ago.
Unfortunately it isnt working at all for me.
Im on linux, I have python 3 and the geckodriver in the project directory.

`Please enter your zyBooks email: collinrijock@gmail.com
Enter your zyBooks password: 

Login Successful

Enter your course ID or the name of your course: FIUCOT3100GandhiWinter2021
zyBook Selected

Enter the chapter number you want completed: 1
Chapter Selected

Enter the section number you want completed. Enter "all" if you would like the entire chapter completed: all

Starting chapter 1 section 1...
Headless Firefox browser closed
`
As soon as it begins to work on the problems it fails. Ive tried other zybooks completers and have looked at the code and maybe zybooks changed the format for the activity requests? They have some metadata tags now for each question and I'm not sure if you handle that. If you want to contact me or try to fix this issue that would be awesome.

**Comment by Djaenk** [comment]
The script appears to work fine on my own account. Can you send a copy of the chapter selection page and the first page of activities? You should be able to right-click and save copy as a complete web page.

**Comment by collinrijock** [comment]
[1.1. Propositions and logical operations.zip](https://github.com/Djaenk/zyBooks-Activity-Completer/files/5862627/1.1.Propositions.and.logical.operations.zip)
Yup here you go. Again maybe its that I am on linux and theres some issue with the geckodriver?

**Comment by Djaenk** [comment]
Can you give me any details about your distro or how you're running it?

**Comment by collinrijock** [comment]
Im running on Fedora 33 with Python 3.9

**Comment by Djaenk** [comment]
Okay, I ran the script on Fedora 33 in a VM and I managed to reproduce the issue, but not with any consistency. The script actually worked as intended more often than it failed; I don't have a clue what causes this problem. My best guess is the problem comes from the geckodriver, seeing as both its webdriver and its integration with selenium are works in progress. I pushed some unrelated bugfixes you can try pulling in the off chance they somehow help.

If you're still unable to get the script working as intended, try commenting out line 280. Turns off headless mode while the script manipulates it. Even if it doesn't stop the driver from crashing on your machine, you will at least be able to see what is happening beforehand.
